// This file is autogenerated by build.rs
pub const IMAGES: &[&[u8]] = &[
    include_bytes!("../.././images/krousiantor_network_diegram.png"),
    include_bytes!("../.././images/1255DA15-5B40-4DAB-A141-6B4FF4B649CE_1_105_c.png"),
    include_bytes!("../.././images/2334A5F0-1358-43D7-BC04-AF2981FDCA2F_1_105_c.png"),
    include_bytes!("../.././images/0C4AF4A4-289D-48B6-B742-CC391192DE9B_1_105_c.png"),
    include_bytes!("../.././images/A62EFF48-D45B-4D98-BB9B-B3FA3EB42F23_1_105_c.png"),
    include_bytes!("../.././images/9F1666A4-12E1-4161-B45A-D8C1283C7A9E_1_105_c.png"),
    include_bytes!("../.././images/B281DCBF-29CE-4553-8EE2-0D23A6257671_1_105_c.png"),
    include_bytes!("../.././images/5B2C7CD7-6EAF-4BD1-9D37-6460CDD96A18_1_105_c.png"),
    include_bytes!("../.././images/E89D24E5-9DB6-485D-9B5B-BACB75C17C59_1_105_c.png"),
    include_bytes!("../.././images/865C69FB-C0C2-4AF1-A870-273FDEFDDD79_1_105_c.png"),
    include_bytes!("../.././images/D58AF453-757E-460A-AC77-FE0C81FFCE72_1_105_c.png"),
];
